matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: bionic
      install:
        - cd nodejs; npm install; cd -;
        - npm install --global mocha@7
        - mkdir -p ${HOME}/Documents/DianrongBaaS-SDK/nodejs/test/artifacts
        - cp -r ${TRAVIS_BUILD_DIR}/nodejs/test/artifacts/crypto-config ${HOME}/Documents/DianrongBaaS-SDK/nodejs/test/artifacts
      script:
        - mocha nodejs/test



