matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: bionic
      cache:
        directories:
          - nodejs/node_modules
      install:
        - cd nodejs; npm install; cd -;
        - npm install --global mocha@7
      script:
        - mocha nodejs/test



